[versions]
minecraft = "1.21.1"
hiiragi-core = "0.2.1"

parchment-mc = "1.21.1"
parchment-map = "2024.11.17"

neo-moddev = "2.0.124"
neo-version = "21.1.216"

dokka = "2.1.0"
kff-version = "5.10.0"
ktlint = "14.0.1"

axion-release = "1.21.1"
maven-publish = "0.35.0"

almost = "1.21.1-1.3.0"
emi = "1.1.22+1.21.1"
jade = "15.10.3+neoforge"
mek = "1.21.1-10.7.17.83"
mi = "2.4.1"

arch = "13.0.8"
guide = "21.1.15"

[libraries]

kff = { group = "thedarkcolour", name = "kotlinforforge-neoforge", version.ref = "kff-version" }

almost = { group = "com.almostreliable.mods", name = "almostunified-neoforge", version.ref = "almost" }
emi = { group = "dev.emi", name = "emi-neoforge", version.ref = "emi" }
jade = { group = "maven.modrinth", name = "jade", version.ref = "jade" }
mek = { group = "mekanism", name = "Mekanism", version.ref = "mek" }
mi = { group = "aztech", name = "Modern-Industrialization", version.ref = "mi" }

arch = { group = "dev.architectury", name = "architectury-neoforge", version.ref = "arch" }
guide = { group = "org.appliedenergistics", name = "guideme", version.ref = "guide" }

[bundles]

mods-impl = [
    "almost",
    "emi",
    "jade",
    # non-direct dependencies
    "arch",
    "guide",
    "mi",
]

mods-transitive = []

mods-compile = []

mods-runtime = []

[plugins]

neo-moddev = { id = "net.neoforged.moddev", version.ref = "neo-moddev" }

dokka = { id = "org.jetbrains.dokka", version.ref = "dokka" }
dokka-javadoc = { id = "org.jetbrains.dokka-javadoc", version.ref = "dokka" }
ktlint = { id = "org.jlleitschuh.gradle.ktlint", version.ref = "ktlint" }

axion-release = { id = "pl.allegro.tech.build.axion-release", version.ref = "axion-release" }
maven-publish = { id = "com.vanniktech.maven.publish", version.ref = "maven-publish" }
